services:
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
