# Generated by Django 4.2 on 2026-01-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datajob',
            index=models.Index(fields=['user', 'created_at'], name='data_ingest_user_id_2899a3_idx'),
        ),
    ]
